@url=http://localhost:8080/api
@json=Content-Type: application/json
###
GET {{url}}

###
POST {{url}}/register
{{json}}

{
    "username": "gylang",
    "password": "password"
}

###
POST {{url}}/login
{{json}}

{
    "username": "gylang",
    "password": "password"
}

###
POST {{url}}/getGrade
{{json}}
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoxMSwiaWF0IjoxNTY5MjEwMTYwLCJleHAiOjE1NjkyMTM3NjB9.NAPv1iDGvRyeqCAh8FkyodQ5FnpG3aLSF6bE9lQZbTo